apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.birdApiName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.birdApiName }}
  template:
    metadata:
      labels:
        app: {{ .Values.birdApiName }}
    spec:
      containers:
      - name: {{ .Values.birdApiName }}
        image: demarauder/bird:latest
        env:
          - name: BIRD_API_HOST
            value: {{ .Values.birdImageApiName }}-service
          - name: BIRD_API_HOST_PORT
            value: "80"
        ports:
        - containerPort: 4201
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.birdApiName }}-service"
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.birdApiName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4201
  type: LoadBalancer