---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bird-hpa
  namespace: api
  labels:
    app: bird
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bird
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # Time to wait before scaling up again
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60  # Can scale up by 100% of current pods every 60 seconds
    scaleDown:
      stabilizationWindowSeconds: 300  # Time to wait before scaling down again
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60  # Can scale down by 50% of current pods every 60 seconds

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bird-image-hpa
  namespace: api
  labels:
    app: bird-image
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bird-image
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # Time to wait before scaling up again
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60  # Can scale up by 100% of current pods every 60 seconds
    scaleDown:
      stabilizationWindowSeconds: 300  # Time to wait before scaling down again
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60  # Can scale down by 50% of current pods every 60 seconds

