name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - solution
    paths:
      - 'bird/**'       
      - 'birdImage/**' 
  pull_request:
    branches:
      - main
    paths:
      - 'bird/**'      
      - 'birdImage/**'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: 
          - directory: bird
            image_name: bird
          - directory: birdImage
            image_name: bird-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ matrix.directory }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image for ${{ matrix.directory }}
      working-directory: ./${{ matrix.directory }}
      run: |
        docker build -t ${{ env.DOCKER_USERNAME }}/${{ matrix.image_name }}:${{ github.sha }} .
        docker tag ${{ env.DOCKER_USERNAME }}/${{ matrix.image_name }}:${{ github.sha }} ${{ env.DOCKER_USERNAME }}/${{ matrix.image_name }}:latest
        
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ env.DOCKER_USERNAME }}/${{ matrix.image_name }}:${{ github.sha }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL'

    - name: Push Docker image for ${{ matrix.directory }}
      run: |
        echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin
        docker push ${{ env.DOCKER_USERNAME }}/${{ matrix.image_name }}:${{ github.sha }} 
        docker push ${{ env.DOCKER_USERNAME }}/${{ matrix.image_name }}:latest
